### PR TITLE
Some fixes and UI rework

### PR DESCRIPTION
**Pull request by bfred-it**
Not perfect but maybe more usable. On mobile now it's just a big ass slider.

### CODE REVIEW

**Comment by bfred-it** [comment]
Also, some workflow suggestions that might end up in the readme:

    # launch app
    node app 4040

    # watch and build
    jade --watch 'browser/index.jade' --out public

    # watch and reload app
    browser-sync start --proxy="http://localhost:4040" --files="public/*"

**Comment by coolaj86** [comment]
I actually like having presets because it's easier for me to set the volume to the level that I want.

I do like the idea of having a larger target for the slider, but I don't like replacing everything with just a slider.

**Comment by bfred-it** [comment]
The point of the huge slider is to make it easier. Sliding it to 33 or 50 or 100 should be just as easy as it is tapping a button, unless you expect it to be exactly 33 (which is unusually ocd :P )

It could be improved further by having it accept taps anywhere on the interface to just make it jump to that point — e.g. if you tap at the very top, the volume is set to 100 — instead of having to drag it.

**Comment by coolaj86** [comment]
Hmmm... I think we could combine our ideas - maybe large target buttons along the right side, a mute at the bottom, a 100% at the top, and a percentage readout at the very top.

**Comment by bfred-it** [comment]
Mute/100% buttons would work. Maybe on a bar at the bottom, to be easily accessible. 

For the exact percentage I don't see the value outside of debugging; volume is usually displayed as a bar, especially on computers.

**Comment by coolaj86** [comment]
I like percentages because it allows me to reproduce an experience.

I'm a DJ and I created this for me to be able to control the volume on occasions when I don't have an assistant and I have to be on the other side of the room with the mic from where the computer and sound is set up.

I usually set my mixer panel to about the same settings every time. If I do my sound test and find that the sweet spot for background music while someone is speaking is right in the 10 - 15% range I want to quickly be able to get in the range and fine tune. For slow dances I may prefer 65 - 70%, for upbeat dances 80-90%.

Having just bars isn't as helpful because different devices will render the size differently. Imagine if I do have someone assisting and I need to say "set it at about 7/8ths" - not as easy as "try 87%".

Likewise, in my car I know that I need to turn the knob to about 27 if I'm driving on the interstate, 32 if I put the windows down, 15-17 if I'm back on a state road going 35 - 45 MPH, 12 if I'm with someone and want to chat.
Why they couldn't have given me a scale out of 100 I don't know, but I wish they had.

I prefer to have an easy-to-find and easy-to-set reference for things like this because I associate the number with the desired atmosphere.

**Comment by bfred-it** [comment]
Gotcha. I see what you're saying. Perhaps it should just have more than one interface.

**Comment by coolaj86** [comment]
That sounds good to me too. If you were to put an advanced button on the one you built that linked to mine that would work for me.

**Pull request closed without merging**
